sudo: required
language: generic

services:
- docker

env:
  global:
  - TERM=dumb
  - MAKEFLAGS='--silent -j3'

#before_cache:
#  # - find parts/qt
#  - rm -fv parts/*/src
#  - rm -fv parts/*/state/stage
#  - rm -fv parts/*/state/prime
#
#cache:
#  directories:
#  - parts/ffmpeg
#  - parts/gyp
#  - parts/libxkbcommon
#  - parts/qt

install:
  - docker volume create --driver local --opt type=tmpfs --opt device=tmpfs --opt o=size=15g --name build
  - docker run --name builder -e TERM -e MAKEFLAGS -v $PWD:$PWD -v build:/build -w $PWD -td snapcore/snapcraft

before_script:
- test $TRAVIS_BRANCH != master || test $TRAVIS_PULL_REQUEST != false &&
  sed 's/build-type:.*/build-type:'\ \'Debug\'/ -i snapcraft.yaml &&
  echo 'Debug' || echo 'Default'

script:
  - travis_wait docker exec -i builder sh -c "cp -ra . /build; cd /build; snapcraft"

#after_success:
#- openssl aes-256-cbc -K $encrypted_1d36a60557dc_key -iv $encrypted_1d36a60557dc_iv
#  -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
#- git checkout -- snapcraft.yaml
#
#before_deploy:
#  - docker exec -i builder snapcraft clean telegram
#  - travis_wait 60 docker exec -i builder snapcraft
#
#deploy:
#  skip_cleanup: true
#  provider: script
#  script: docker exec -i builder snapcraft push *.snap --release edge
#  on:
#    branch: master
#    # condition: $TRAVIS_PULL_REQUEST = false
#    # tags: true
