sudo: required
language: generic

services:
- docker

env:
  global:
  - TERM=dumb
  - MAKEFLAGS='--silent -j3'
  matrix:
  - PART="ffmpeg"
  - PART="gyp"

before_cache:
   - echo "Caching:"
   - find parts

cache:
  directories:
   - parts

install:
  - docker run --name builder -e TERM -e MAKEFLAGS -v $PWD:$PWD -w $PWD -td snapcore/snapcraft

before_script:
- test $TRAVIS_BRANCH != master || test $TRAVIS_PULL_REQUEST != false &&
  sed 's/build-type:.*/build-type:'\ \'Debug\'/ -i snapcraft.yaml &&
  echo 'Debug' || echo 'Default'

script:
  - docker exec -i builder snapcraft prime $PART

after_success:
  - docker exec -i builder snapcraft
